### ISSUE TITLE
Stuck during MetaWorks_v1.12.0 Tutorial

### ISSUE THREAD

**Issue by ejlaqua** [terrimporter/MetaWorks#10]
Hi! I’m also experiencing difficulty with the MetaWorks_v1.12.0 tutorial similar to the following two posts:

1. https://github.com/terrimporter/MetaWorks/issues/5
2. https://github.com/terrimporter/MetaWorks/issues/8

I tried following the solutions posted in those two threads but I haven't been able to figure it out and the tutorial isn’t working. I’m new to Linux and MetaWorks. I’m using Ubuntu with the WSL2. My laptop has 10 cores and 16gb ram installed. 

**A.** When I typed `echo $SHELL` during the tutorial I got 

> /bin/bash

so I ran `conda init bash` to initialize conda for that step.

**B.** When I go to the rRNAClassifier.properties file (while in the Linux command terminal) and enter `pwd` I get: 

> /home/ocean/MetaWorks1.12.0/mydata

So I updated my path in config_testing_COI_data.yaml to be:

> t: "/home/ocean/MetaWorks1.12.0/mydata/rRNAClassifier.properties"

**C.** After following the rest of the steps in the tutorial I tried to run `snakemake --jobs 2 --snakefile snakefile_ESV --configfile config_testing_COI_data.yaml` but I got the same "java heap space" memory error as this post (1.https://github.com/terrimporter/MetaWorks/issues/5) so I also tried changing -Xmx8g to -Xmx16g in config_testing_COI_data.yaml.

**D.** Now when I run `snakemake --jobs 2 --snakefile snakefile_ESV --configfile config_testing_COI_data.yaml` with -Xmx16g I get the following message:

> Building DAG of jobs...
> Using shell: /usr/bin/bash
> Provided cores: 2
> Rules claiming more threads will be scaled down.
> Job stats:
> job                                   count    min threads    max threads
> ----------------------------------  -------  -------------  -------------
> add_good_orf_sequences_to_taxonomy        1              1              1
> all                                       1              1              1
> consolidate_orfs                          1              1              1
> filter_ESV_table                          1              1              1
> filter_rdp                                1              1              1
> get_orfs_aa                               1              1              1
> get_orfs_nt                               1              1              1
> get_results                               1              1              1
> hmmscan                                   1              1              1
> subset_ESV_sequences_by_taxon             1              1              1
> subset_taxonomy_by_taxon1                 1              1              1
> taxonomic_assignment                      1              1              1
> total                                    12              1              1
> 
> Select jobs to execute...
> 
> [Fri Aug 25 18:49:48 2023]
> rule taxonomic_assignment:
>     input: COI/cat.denoised.nonchimeras
>     output: COI/rdp.out.tmp
>     jobid: 37
>     reason: Missing output files: COI/rdp.out.tmp
>     resources: tmpdir=/tmp
> 
> Building DAG of jobs...
> Using shell: /usr/bin/bash
> Provided cores: 2
> Rules claiming more threads will be scaled down.
> Select jobs to execute...
> /home/ocean/miniconda3/envs/MetaWorks_v1.12.0/bin/rdp_classifier: line 57:    84 Killed                  /home/ocean/miniconda3/envs/MetaWorks_v1.12.0/bin/java -Xmx16g -jar /home/ocean/miniconda3/envs/MetaWorks_v1.12.0/share/rdp_classifier-2.13-1/classifier.jar classify -t /home/ocean/MetaWorks1.12.0/mydata/rRNAClassifier.properties -o COI/rdp.out.tmp COI/cat.denoised.nonchimeras
> [Fri Aug 25 18:50:15 2023]
> Error in rule taxonomic_assignment:
>     jobid: 0
>     input: COI/cat.denoised.nonchimeras
>     output: COI/rdp.out.tmp
> 
> RuleException:
> CalledProcessError in file /home/ocean/MetaWorks1.12.0/snakefile_ESV, line 343:
> Command 'set -euo pipefail;  rdp_classifier -Xmx16g classify -t /home/ocean/MetaWorks1.12.0/mydata/rRNAClassifier.properties -o COI/rdp.out.tmp COI/cat.denoised.nonchimeras' returned non-zero exit status 137.
>   File "/home/ocean/MetaWorks1.12.0/snakefile_ESV", line 343, in __rule_taxonomic_assignment
>   File "/home/ocean/miniconda3/envs/MetaWorks_v1.12.0/lib/python3.10/concurrent/futures/thread.py", line 58, in run
> Removing output files of failed job taxonomic_assignment since they might be corrupted:
> COI/rdp.out.tmp
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: .snakemake/log/2023-08-25T184946.566586.snakemake.log

**Comment by ejlaqua** [comment]
> 1. Can you double check that you have activated the MetaWorks_v1.12.0 environment file?
> 2. Can you run the rdp_classifier from the command line to ensure that the program is properly starting? You can paste /home/labecmar/miniconda3/envs/MetaWorks_v1.12.0/share/rdp_classifier-2.13-1/classifier.jar or try just using rdp_classifier to see if it calls the program.
> 3. Can you check that the COI/cat.denoised.nonchimeras file has content?

Based on the above questions from https://github.com/terrimporter/MetaWorks/issues/9 I'd also like to add:

1. Yes I am in `(MetaWorks_v1.12.0) ocean@NB-361:~/MetaWorks1.12.0/COI$` not `(base) ocean@NB-361:~/MetaWorks1.12.0/COI$ `so I have activated the MetaWorks_v1.12.0 environment file.
2. When I run just `(MetaWorks_v1.12.0) ocean@NB-361:~/MetaWorks1.12.0$ rdp_classifier` I get:
> USAGE: ClassifierMain <subcommand> <subcommand args ...>
> default command is classify
>         classify      - classify one or multiple samples
>         crossvalidate - cross validate accuracy testing
>         comp-trainset - compare multiple training sets to find shared and unique taxa and sequences
>         libcompare    - compare two samples
>         loot          - leave one (sequence or taxon) out accuracy testing
>         merge-detail  - merge classification detail result files to create a taxon assignment counts file
>         merge-count   - merge multiple taxon assignment count files to into one count file
>         random-sample - random select a subset or subregion of sequences
>         rm-dupseq     - remove identical or any sequence contained by another sequence
>         rm-partialseq - remove partial sequences
>         taxa-sim      - calculate and plot the similarities within taxa
>         train         - retrain classifier
>         version       - taxonomy versions of the pre-compiled training sets
3. COI/cat.denoised.nonchimeras has content

I'm very new to this so I'm not sure if I've got all the parts of MetaWorks from the tutorial set up in the correct directories and I hope I didn't put something in the wrong location!

**Comment by terrimporter** [comment]
You've done a great job troubleshooting.  Let me take a look and get back to you.

**Comment by terrimporter** [comment]
Can you send me your config_testing_COI_data.yaml file so I can take a look?

**Comment by ejlaqua** [comment]
Ok here's config_testing_COI_data.yaml copied as a .txt file!
[config_testing_COI_data.yaml.txt](https://github.com/terrimporter/MetaWorks/files/12446541/config_testing_COI_data.yaml.txt)

**Comment by ejlaqua** [comment]
I think I was able to solve my issue by increasing my swap space. Before it had been set at 2 GB and I tried increasing it to either 8 GB or 16 GB and both worked. I followed the steps here: https://askubuntu.com/questions/178712/how-to-increase-swap-space

In MetaWorks, I got a results.csv from the testing data and the following message after running snakemake:

> [Tue Aug 29 16:27:01 2023]
> Finished job 0.
> 9 of 9 steps (100%) done
> Removing temporary output testing/COI_results/stats/COI-1-1-BR5-F230R_S13.Pstats.
> Removing temporary output testing/COI_results/stats/COI-1-2-BR5-F230R_S14.Pstats.
> Removing temporary output testing/COI_results/stats/COI-1-1-BR5-F230R_S13.trimmedstats.
> Removing temporary output testing/COI_results/stats/COI-1-2-BR5-F230R_S14.trimmedstats.
> Complete log: .snakemake/log/2023-08-29T162656.284282.snakemake.log

**Comment by terrimporter** [comment]
If you're having memory problems generating the last results.csv file, then either you are trying to process many reads or your system may not have enough memory to combine the ESV table with the taxonomy.  You could try the other output option that keeps these two files separate.  As for your message above, those final statements are just letting you know that un-needed files are being removed to save space on your system.
