### ISSUE TITLE
No rRNAclassifier.properties files for 12SvertebrateClassifier and 16SvertebrateClassifier?

### ISSUE THREAD

**Issue by ejlaqua** [terrimporter/MetaWorks#11]
Hello! When I downloaded new classifiers for MetaWorks like the 18SClassifier (https://github.com/terrimporter/18SClassifier) from the list of classifiers (https://terrimporter.github.io/MetaWorksSite/#classifier_table) I was able to successfully follow the quickstart guidelines and locate its rRNAClassifier.properties file in order to run the new classifier with my own practice data.

<img width="577" alt="image" src="https://github.com/terrimporter/MetaWorks/assets/143235511/caab5777-dd47-4819-9a1c-39a4155c4fca">

However, when I tried to download both the 12SvertebrateClassifier (https://github.com/terrimporter/12SvertebrateClassifier) and the 16SvertebrateClassifier (https://github.com/terrimporter/16SvertebrateClassifier) there was no quick start guide on the GitHub page. When I downloaded and unzipped the .zip source code file, .tar.gz source code file, and the mydata_training.tar.gz files I was unable to locate the rRNAClassifier.properties file.

<img width="467" alt="image" src="https://github.com/terrimporter/MetaWorks/assets/143235511/c9da662f-a8da-4340-8ea0-6fb53dd2b367">

<img width="838" alt="image" src="https://github.com/terrimporter/MetaWorks/assets/143235511/2e7b20ec-0ec4-4cfb-a7eb-f0651734b5dc">

Additional guidance on how to use the 12SvertebrateClassifier and 16SvertebrateClassifier with MetaWorks and the RDP classifier would be appreciated! I'm new to MetaWorks and Linux and I'm missing why setting up these two classifiers is different from setting up the other MetaWorks classifiers I've tried so far. Thank you!

**Comment by terrimporter** [comment]
Hi, I just checked the 12S vertebrate classifier version 3 (North America) and version 2 and both have rRNAclassifier.properties files.  Just make sure you're not downloading the '-ref' versions which are only provided in case you want access to the underlying FASTA file.  As for the 16S vertebrate classifier, I checked that one too and it's fine.  Just ensure you're using the 'trained' not 'training' version (same reason as above).  Sorry there's no quickstart provided, but you use these with Metaworks just like the other versions of the classifier, you can name the directories whatever you like, just keep track of the path to the rRNAclassifier.properties file.

**Comment by ejlaqua** [comment]
Thank you! I think I made a mistake and was accidentally trying to download the incorrect -ref files the first time. It's working now! I was also wondering, if I'm trying to specify the 16S vertebrate classifier in config_ESV.yaml should I select "16S" here? Is "16S" for both the built-in 16S prokaryote classifier and the downloaded 16S vertebrate classifier? I see multiple options for 12S but only one option for 16S.

<img width="862" alt="image" src="https://github.com/terrimporter/MetaWorks/assets/143235511/d1e08d03-4004-4177-a935-82566c9edd4b">
<img width="846" alt="image" src="https://github.com/terrimporter/MetaWorks/assets/143235511/3282f13e-80c8-47c7-82f1-a321a67788d9">

**Comment by terrimporter** [comment]
I just updated MetaWorks to v1.13.0 to support the mitochondrial 16S vertebrate classifier.  You should now see it listed in the configuration file as an option.  Thanks, -t

**Comment by ejlaqua** [comment]
Thank you for your help!
