### ISSUE TITLE
Can MetaWorks Start with Contigs?

### ISSUE THREAD

**Issue by NailouZhang** [terrimporter/MetaWorks#12]
Hi,
Can MetaWorks Start with Contigs? I know BOLDigger can start with contigs, but just with 50 sequences at one time. Locally running with metaworks can be worked within a pipeline.

**Comment by terrimporter** [comment]
MetaWorks does a whole lot of quality control steps (pairing, trimming, denoising, etc) plus taxonomic assignments.  If I'm not mistaken, BOLDigger is primarily used just for taxonomic assignments?  If that is all you need, you don't need to run the full MetaWorks pipeline.  You can use the 'clean' contigs you already have and use the RDPclassifier on it's own, at the command line, along with the custom training set you need.   You can find the instructions here if you like https://github.com/terrimporter/CO1Classifier

**Comment by NailouZhang** [comment]
Thanks a lot
