### ISSUE TITLE
Is there a version of this pipeline we can use on Windows ? 

### ISSUE THREAD

**Issue by Roxe4228** [terrimporter/MetaWorks#3]
Hi ! 
I really want to try this pipeline with my sequences, but I only have a laptop so I can't install Linux on it. I was then wondering if there is any version of this pipeline that we can use on windows ? I know we can install Python, Conda & Miniconda on windows. 
Thanks a lot for your response !

**Comment by terrimporter** [comment]
The programs that MetaWorks uses are largely meant to be run on linux.  I normally run pipelines on a high performance computing cluster as this is the most efficient way for many datasets.  If you are at a university, you might like to check with others in your department to see if you have an HPC environment available for you to access (there almost always is).  The alternative, is to run linux programs in a linux partition on your windows computer.
