### ISSUE TITLE
vsearch versioning

### ISSUE THREAD

**Issue by mlbowser-usfws** [terrimporter/MetaWorks#6]
The version of vsearch included in the MetaWorks_v1.11.0 conda environment ( v2.15.2) does not implement `--fastx_uniques` in the dereplicate rule in the snakefile_ESV file. This was not implemented in vsearch until version 2.20.0 (see <https://github.com/torognes/vsearch/issues/348>).

**Comment by terrimporter** [comment]
I recently updated the environment file to include the correct version of VSEARCH, can you download it again, it should work fine now.

**Comment by mlbowser-usfws** [comment]
Thank you, @terrimporter! Thank you, also, for maintaining, updating, and making MetaWorks available.
