### ISSUE TITLE
snakemake version

### ISSUE THREAD

**Issue by anslan** [terrimporter/MetaWorks#7]
Hi,
does the snakemake version matter for running MetaWorks (e.g. v1.11.2); i.e. can I use snakemake v6.7.0. Later versions of snakemake cause issues while running through docker container.

Cheers,
Sten

**Comment by terrimporter** [comment]
The conda environment I provide should already come with a version of snakemake that works with the pipeline, but if you're having problems with that version, then I'd just use whatever version runs the pipeline.  I'll keep an eye on this when testing future versions.
