### ISSUE TITLE
Difficuty with MetaWorks 12.0 Tutorial

### ISSUE THREAD

**Issue by Jess-Schultz** [terrimporter/MetaWorks#8]
Hi there!
I am also experiencing difficulty with the Tutorial.  I am new to coding and MetaWorks.  I have edited the path to the classifier in the config_testing_COI_data.yaml file, but am still getting the following error: 

Error in rule taxonomic_assignment:
    jobid: 0
    input: COI/cat.denoised.nonchimeras
    output: COI/rdp.out.tmp

RuleException:
CalledProcessError in file /home/innovation-admin/MetaWorks1.12.0/snakefile_ESV, line 343:
Command 'set -euo pipefail;  rdp_classifier -Xmx8g classify -t /home/innovation-admin/MetaWorks1.12.0/mydata/rRNAClassifier.properties -o COI/rdp.out.tmp COI/cat.denoised.nonchimeras' returned non-zero exit status 1.
  File "/home/innovation-admin/MetaWorks1.12.0/snakefile_ESV", line 343, in __rule_taxonomic_assignment
  File "/home/innovation-admin/miniconda3/envs/MetaWorks_v1.12.0/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job taxonomic_assignment since they might be corrupted:
COI/rdp.out.tmp

Any suggestions on what might be going wrong?
Thank you for your help.

_Originally posted by @Jess-Schultz in https://github.com/terrimporter/MetaWorks/issues/5#issuecomment-1646028223_

**Comment by Jess-Schultz** [comment]
Apologies - moving this to a new thread. 
Thanks for your quick reply!  Now that I've increased the memory to 16, I am getting this error instead:

Error in rule get_orfs_aa:
    jobid: 38
    input: COI/chimera.denoised.nonchimeras.taxon
    output: COI/orfs.fasta.aa
    shell:
        ORFfinder -in COI/chimera.denoised.nonchimeras.taxon -g 5 -s 2 -ml 30 -n true -strand plus -outfmt 0 > COI/orfs.fasta.aa
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job get_orfs_aa since they might be corrupted:
COI/orfs.fasta.aa
[Fri Jul 21 14:47:44 2023]
Error in rule get_orfs_nt:
    jobid: 34
    input: COI/chimera.denoised.nonchimeras.taxon
    output: COI/orfs.fasta.nt
    shell:
        ORFfinder -in COI/chimera.denoised.nonchimeras.taxon -g 5 -s 2 -ml 30 -n true -strand plus -outfmt 1 > COI/orfs.fasta.nt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job get_orfs_nt since they might be corrupted:
COI/orfs.fasta.nt
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by terrimporter** [comment]
Good, so the classifier is working now.

Have you checked that ORFfinder is properly installed?  ex. if you just type ORFfinder on the command line, do you see the help or instructions asking for an infile or do you get an error?

**Comment by Jess-Schultz** [comment]
Thank you, I think I see the problem.  I installed ORFfinder as per the tutorial instructions, but what I thought was the /home/bin folder is actually within a user folder and is therefore not in the $PATH directory. I can't fix it presently as I do not have the necessary permissions, but once I have I will try running the test script again.
Thanks for your help and patience!

**Comment by terrimporter** [comment]
Actually, if you do 'echo $SHELL' at the command line you can figure out what shell you're using.  Then you can add the /home/bin folder to your PATH by adding it to the .bashrc file if you're using bash.  You can google the syntax.
